### PR TITLE
Add Rails and Ruby related resources

### PR DESCRIPTION
**Pull request by shubhpatel108**
- Adding links to books, courses, tutorials related to Rails
- Adding links to blogs, books, tutorials and some other useful links related to Ruby language

Keeping resources related to Ruby and Rails in the same directory sends a misleading message. Both are different. Ruby is a language and Rails is MVC based web framework built using Ruby; Similar to Python and Django.

### CODE REVIEW

**Comment by PSanni** [comment]
@shubhpatel108  It's good if you please follow [this](https://github.com/GDGAhmedabad/Learning-Resources/blob/master/Python/books.md) format.

**Comment by rathodchintan** [comment]
@shubhpatel108 Good to see you here. But PR has Conflicts! Please take update and PR again. :)

**Comment by PareshMayani** [comment]
@rathodchintan no need to send new PR but just need to resolve conflicts in this PR itself!

**Comment by rathodchintan** [comment]
Ok @PareshMayani. @shubhpatel108  can you please resolve conflicts. :)

**Comment by shubhpatel108** [comment]
@rathodchintan @PareshMayani Done with the conflicts. Shall I convert the links to [this](https://github.com/GDGAhmedabad/Learning-Resources/blob/master/Python/books.md) format?

**Comment by PareshMayani** [comment]
Thank you @shubhpatel108 for the contribution. Really appreciate it. Look forward for more :)

**Pull request merged**
