### PR TITLE
add Saúl Molinero's blog

### PR DESCRIPTION
**Pull request by PareshMayani**

### CODE REVIEW

**Comment by rathodchintan** [comment]
Branch conflicts @PareshMayani. I guess https://github.com/GDGAhmedabad/Learning-Resources/pull/105/files commit has that blog link.

**Comment by PareshMayani** [comment]
No this is different link! I will resolve this conflict and will send commit!

**Comment by rathodchintan** [comment]
Yes. I checked, its different one. :)

**Comment by PareshMayani** [comment]
It will require another commit to resolve this conflict and 2 commits should not be pushed for a single line contribution! Will send another PR

**Pull request closed without merging**
