### PR TITLE
GoLang directory added

### PR DESCRIPTION
**Pull request by ashwini0529**
GoLang is very powerful and fast growing Language. Need to be added too.

### CODE REVIEW

**Comment by PareshMayani** [comment]
Are you going to share some links/resources for the Go? Or you just created a directory?

**Comment by ashwini0529** [comment]
I'll be sharing links too. Also, at our [GDG VIT VELLORE] (https://github.com/GDGVIT) we have very good GoLang developers. I'll ask them to share links to GoLang. As well as to other languages.

**Comment by ashwini0529** [comment]
@shubhothegreat, please contribute to the GoLang directory.

**Comment by PareshMayani** [comment]
Awesome. Thanks for joining hands for this initiative!

**Comment by PareshMayani** [comment]
My point was actually committing into this PR itself but now as you haven't created a branch specifically for this PR, so it would be hard for you to share more commits! So I am closing down this PR but I think you should create a separate branch for each PR, this would save you from conflicts and also allow you to save time!

**Comment by ashwini0529** [comment]
We're always there to contribute in open community. And yes, I'll keep in mind for creating individual branches.

**Pull request merged**
