### PR TITLE
Login Demo with DataBinding

### PR DESCRIPTION
**Pull request by ravirupareliya**
Simple login demo which will cover 2-way binding also.

Deleted almost all auto generated files, let me know in case any one i missed to remove.

### CODE REVIEW

**Comment by rathodchintan** [comment]
Should remove **local.properties** file.

**Comment by ravirupareliya** [comment]
@rathodchintan deleted local.properties but it made new commit in this PR, is it fine? or should i create new PR with only one commit?

**Comment by rathodchintan** [comment]
It's fine. :)

**Comment by PareshMayani** [comment]
Looks complete to me. Thank you for preparing demo and there by making contribution! Look forward for such an awesome contribution :)

**Pull request merged**
