### PR TITLE
Add useful libraries

### PR DESCRIPTION
**Pull request by PareshMayani**

### CODE REVIEW

**Comment by rathodchintan** [comment]
PM, do we require to delete branch after each merge?

**Comment by PareshMayani** [comment]
@rathodchintan Please don't merge branch until I ask you for the review and merge. Actually I wanted to add more commits into the same branch!

**Comment by rathodchintan** [comment]
Oh.. sorry for my early merge. Will wait for your message. Then can we revert it back?

**Comment by PareshMayani** [comment]
Nope please don't revert back it now!

**Pull request merged**
