### PR TITLE
Adding Backbone JS

### PR DESCRIPTION
**Pull request by rishiip**
Adding useful links, blogs, video tutorial for beginners, books for backbone js.

### CODE REVIEW

**Comment by rathodchintan** [comment]
As per guideline, we are expecting books' purchase link. So can you please update those links which are pointing to Dropbox and PR again. 

Ref: https://github.com/GDGAhmedabad/Learning-Resources/issues/78#issuecomment-202323092

**Comment by rishiip** [comment]
@rathodchintan : My Bad :weary: Thanks for suggesting. I had updated PR with book purchase links! You may merge it now.

**Comment by rathodchintan** [comment]
@rishiip Thanks for your immediate update.

**Comment by PareshMayani** [comment]
@rathodchintan looks complete to me, you can merge it!

**Pull request merged**
