### PR TITLE
Add TextInputLayout Demo

### PR DESCRIPTION
**Pull request by rathodchintan**
Add TextInputLayout Demo with color effect and applied font style

### CODE REVIEW

**Comment by PareshMayani** [comment]
As we discussed, please don't commit auto generated files and directories!

**Comment by rathodchintan** [comment]
@PareshMayani can you please point out which are auto generated files I committed? I crossed checked with your Retrofit example and then committed.

**Comment by PareshMayani** [comment]
I think that was a mistake when I committed Retrofit example but later we decided not to commit auto generated files and directories like build. Ideally we should not commit!

**Comment by rathodchintan** [comment]
Ok. So let me remove build.gradle file and pull again. :)

**Comment by PareshMayani** [comment]
Thank you @rathodchintan for the contribution. Keep up adding more examples!

**Comment by rathodchintan** [comment]
yeah.. !! :)

**Pull request merged**
