### PR TITLE
DataBinding update values onClick of button demo

### PR DESCRIPTION
**Pull request by ravirupareliya**

### CODE REVIEW

**Comment by PareshMayani** [comment]
Note: Please don't commit auto generated files/directories like build folder.

**Comment by ravirupareliya** [comment]
I have deleted all autogenerated files, infact compared folder structure with chintan's demo.

**Comment by PareshMayani** [comment]
Yes @rathodchintan also did a mistake in committing those folder, let's not repeat that mistake again!

**Comment by PareshMayani** [comment]
Thank you @ravirupareliya for the data binding button click demo. Look forward for more such examples/demos and awesome contribution!

**Comment by ravirupareliya** [comment]
Thank you , and sorry for those silly mistakes, will take care from next time.

**Comment by PareshMayani** [comment]
No problem! eventually you will learn and will not repeat such mistakes! Anyway, contribution matters a lot :)

**Pull request merged**
