### PR TITLE
Add Course Link for Go

### PR DESCRIPTION
**Pull request by S2606**
Added a link for a basic course in Go programming language.

### CODE REVIEW

**Comment by rathodchintan** [comment]
Hi @S2606, can you check guideline for adding course (Ref: [Android](https://github.com/GDGAhmedabad/Learning-Resources/blob/master/android/courses.md))

**Comment by PareshMayani** [comment]
@rathodchintan this is not an issue, we will improve formatting later on. If this is coming more often from contributors then that's an issue!

@S2606 please follow guidelines/formatting next contributions onwards. Thanks for your current contribution, looking forward for more!

**Comment by rathodchintan** [comment]
@PareshMayani Ok.. I will deprioritize formatting.

**Comment by S2606** [comment]
@PareshMayani Thank you and I shall take care of it next time.

**Pull request merged**
