### PR TITLE
Inserted list of Performance and Complexity tips for python and Project list for beginners.

### PR DESCRIPTION
**Pull request by PSanni**
I have included few major important tips on Performance and Complexity. We call it Gold lime. 
It might be hard to understand for beginners, but experience  developer could easily get it. So, it's on you to either merge or not. I personally suggest to add. :+1: 

Project List commit contains list of projects, beginners could implement in any programming language to sharpen their skills.

### CODE REVIEW

**Comment by PareshMayani** [comment]
@PSanni that's an excellent list. Superb!

But again an issue here is you have shared projects list and python tips/tricks, both of these things are different. In future, please send a separate PR if you want to share different things for the different technologies!

**Comment by PSanni** [comment]
Ya, Sure. Will take care of it.

**Comment by PSanni** [comment]
@PareshMayani Would you merge this request or should i make new separate PR ???.

**Comment by PareshMayani** [comment]
@PSanni actually this was assigned for the review. As per the review this is high level tips/tricks, should contain short/possible code to support it. Let's not merge it until you prepare a list with possible code.

But project list is an awesome list, could you please send it in a separate PR?

**Comment by PSanni** [comment]
@PareshMayani No offense on your decision, but i would like to admit that, the Zen of Python(PEP20) written here are Python official recommended lines every developer should understand. (https://www.python.org/dev/peps/pep-0020/). Few of them could not be described in code because those are concept, but i 'ii try out to write description for every Zen. :+1:

**Pull request closed without merging**
