### PR TITLE
Python Courses

### PR DESCRIPTION
**Pull request by PSanni**
I have added few free python courses, from well known webSites.

### CODE REVIEW

**Comment by rathodchintan** [comment]
Have you checked preview of your commit? Please check one time. Please make sure you format text very well so that other users can easily read it.

**Comment by PareshMayani** [comment]
Hi @PSanni, thank you for the contribution! 

Regarding your commits, there is a formatting issue!

We request you to send another PR with a single commit with following proper formatting. You can take this file as a reference https://github.com/GDGAhmedabad/Learning-Resources/blob/master/android/Useful_links.md

**Comment by PSanni** [comment]
Got it.

**Comment by PareshMayani** [comment]
Closing this PR! Looking forward for your next PR and awesome contribution

**Pull request closed without merging**
