### PR TITLE
PWA Learning resources.

### PR DESCRIPTION
**Pull request by hirendave**
Advanced features of PWA like fetch API, indexed db, PWA lighthouse
tool and how to create PWA with JavaScript Frameworks.

### CODE REVIEW

**Comment by rathodchintan** [comment]
@hirendave Thanks for your contribution. 
But can you check Contribution guideline and send us another PR as you didn't follow structure. Current PR is example of PWA if I am not wrong. So, you can create a "PWA -> examples_demos". Check [this android](https://github.com/GDGAhmedabad/Learning-Resources/tree/master/android) directory structure for more information

**Comment by rathodchintan** [comment]
@hirendave Thanks for your contribution. 👍

**Comment by PareshMayani** [comment]
@hirendave how about creating more examples which would help community members in exploring and learning concepts of PWA in combination of different frameworks like Angular, Node.js, etc

**Comment by hirendave** [comment]
Sure, @PareshMayani . My plan is work on blog series on PWA where I will cover everything related to it. For the series I will create examples that will add here.

**Comment by PareshMayani** [comment]
@hirendave looking forward for your series and examples contribution. Thanks!

**Pull request merged**
