### PR TITLE
Added two more tools

### PR DESCRIPTION
**Pull request by milaptank**
feature-graphic-generator and Genymotion

### CODE REVIEW

**Comment by PareshMayani** [comment]
Milap, please follow the format followed in Debug and JSON categories. I mean to say leave space wherever required and put "-" between link and description.

**Comment by PareshMayani** [comment]
I am keeping this PR open so that you can add more tools into the same PR!

**Comment by milaptank** [comment]
Okey i will keep in mind for for format followed by other category and yes i have more tools to add that i will add ASAP

**Comment by PareshMayani** [comment]
sure, you can add those commits into this PR only and please try to keep less number of commits!

**Comment by PSanni** [comment]
PR having conflicts, should be closed now.

**Comment by rathodchintan** [comment]
@PareshMayani Can we close this PR?

**Comment by milaptank** [comment]
let me add some tool and i will commit

**Comment by PareshMayani** [comment]
Closing this PR as requested by Sanni! Thanks

**Comment by rathodchintan** [comment]
@milaptank But this branch has conflicts. So need to first resolve and then you have to PR again.

**Pull request closed without merging**
