### PR TITLE
add retrofit 2.0 basic example

### PR DESCRIPTION
**Pull request by PareshMayani**
Add a basic example used during Retrofit 2.0 hands-on event.

### CODE REVIEW

**Comment by PareshMayani** [comment]
@rathodchintan please verify and merge it if it looks good :)

**Comment by rathodchintan** [comment]
Can you please provide **Write access** to this repository.

**Comment by PareshMayani** [comment]
Given, please check now!

**Comment by rathodchintan** [comment]
Got it.. Thanks..

**Comment by PareshMayani** [comment]
Thank you :+1:

**Pull request merged**
