### PR TITLE
Add Data Structure Demos

### PR DESCRIPTION
**Pull request by rathodchintan**
Add BFS, DFS and Max heap example

### CODE REVIEW

**Comment by PSanni** [comment]
Great. :+1:  very old code i think. :wink:

**Comment by rathodchintan** [comment]
Yes. At time of my bachelor's. But still when Data structure is there in syllabus, these programs are always there. Hope some students will get benefit of it. :)

**Comment by PareshMayani** [comment]
@PSanni old is gold :) And data and file structure is always a hot favorite topic when you go for interview in any MNC!

**Comment by PSanni** [comment]
Yup, mostly in google telephonic and technical interview.

**Comment by PareshMayani** [comment]
@PSanni not in Google but also in Flipkart, Samsung, Ola #MyPersonalExperience ;)

**Pull request merged**
