### PR TITLE
Add TOC

### LINKED ISSUE #51: Link all other files in repo's README.md
I propose a structure like this . 
- Angular
- Git
  - [Books]()
  - [Courses]()
  - [Podcasts]()
- Wordpress
  - [Books]()
  - [Blogs]()

This will hopefully make finding what you want much more convenient.

### PR DESCRIPTION
**Pull request by aviaryan**
Fixes #51

@PareshMayani please review

### CODE REVIEW

**Comment by PareshMayani** [comment]
Looks good to me. I am also thinking about following the same structure as in https://github.com/KotlinBy/awesome-kotlin, but I think this would not work for our case as we are having many more technologies and things to cover, so single page would not work! What do you say?

**Comment by aviaryan** [comment]
@PareshMayani Do you mean adding articles, videos etc by month and user groups, webinars, slides and so? 
Well, yes. Our one-page readme may become very large in the future if we do so. Also maintaining something so diverse and vast will require a dedicated team.

**Comment by PareshMayani** [comment]
Yes it would go large as we are managing a lot of resources for many technologies.

**Comment by PareshMayani** [comment]
Thanks for adding TOC.

**Comment by aviaryan** [comment]
@PareshMayani My pleasure 😀

**Pull request merged**
