### PR TITLE
Update Useful_links.md

### PR DESCRIPTION
**Pull request by milaptank**
added Development tools that help developer code easy

### CODE REVIEW

**Comment by rathodchintan** [comment]
Before committing, please cross check whether someone has created a category for supposed tool or not. In your case, I can see JSON category and you have committed links in "Development Tools". So please move them to JSON category and request a PR again.

**Comment by PareshMayani** [comment]
No his commit absolutely correct, it should go under "development tools" category only.

**Comment by rathodchintan** [comment]
Ok. My bad. :)

**Comment by PareshMayani** [comment]
Thank you @milaptank for sharing a list of awesome development tools!

**Pull request merged**
